### PR TITLE
Migrate particle-cli to CircleCI

### PR DESCRIPTION
**Pull request by DebbieGillespie**
Story details: https://app.shortcut.com/particle/story/102023

Migrate CI from Travis to CircleCI.  

Notable changes/notes
  * Drops support for testing Node 8 and Node latest
  * Adds support for testing Node 14 and 16
  * Adds support for testing on Windows
  * [Coverage report](https://output.circle-artifacts.com/output/job/d8cff8c9-7358-46fc-a5d9-dfde4edaa589/artifacts/0/coverage/index.html) is accessible from the Artifacts tab of the run of the test-coverage job.
  * Drops notifications to slack channel
  * e2e tests run in sequence so as to ensure we do not encounter conflicts as they cannot run in parallel
  * Drops support for [LibraryAddCommand](https://github.com/particle-iot/particle-cli/pull/619/commits/ce8f5bd93c387d415cf4702ec271e1e0c2b589ed) as it was intermittently timing out and causing tests to fail
  * Not clear how to test the npm publish given this is a public repo

### CODE REVIEW

**Comment by DebbieGillespie** [comment]
@busticated I have the unit tests running for multiple versions of node on both MacOS and Linux. The node 8 tests are failing due to the following error:
```
Requires optional dependency:
     Error: Cannot find module 'usb'
```
Before I dig into this, want to confirm that we still want to test on node 8. If yes, any suggestions on how to get the usb dependency to installed for node8?

**Comment by monkbroc** [comment]
I took a stab at running the tests on Windows as well. I skipped running the e2e tests since the failures there were harder to debug.

The main source of failures I'm seeing is that we're now running several e2e tests in parallel and they sometimes conflict with each other, for example removing a device from the product in one job but expecting it to be in the product in another job. It might be best to run e2e tests in sequence but then the tests will be super slow.

**Comment by monkbroc** [comment]
This unit test frequently fails so I'd advocate removing it
```
  1) LibraryAddCommand
       adds a library to a project:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/distiller/project/src/cli/library_add.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

**Comment by monkbroc** [comment]
I'm glad to see all the :heavy_check_mark: on the CircleCI checks! Mirande, I put the E2E tests in a sequence to avoid false failures when tests for the same feature ran in parallel.

**Review by monkbroc — APPROVED** [review]
Looks great to me. Mirande, does the CI setup meet your expectations?

**Review by busticated — APPROVED** [review]
looks good - thanks y'all 🙏 👍

**Pull request merged**
