### PR TITLE
Flash files locally

### PR DESCRIPTION
**Pull request by monkbroc**
Adds the functional flasher loop with the progress bar.

### CODE REVIEW

**Comment by monkbroc** [comment]
I'll take a look at CI

**Review by hugomontero — APPROVED** [review]
LGTM! 
```
// When reopening a device that was about to reset, give it some time to boot into the firmware
const REOPEN_DELAY = 3000;
```

this is not being used anymore that's the lint error hehe

**Review by keeramis — APPROVED** [review]
LOOKS GOOD! A few observations:
1. Tracker on dfu mode. Switching 'device to normal mode' didn't respond. 🤔 
```

Memory use:
    Flash      RAM
     4000      436

Flashing tracker e00fce680d2c75c844999283
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | Switching device to normal mode
StateError
    at klass.reset (/Users/keerthyamisagadda/code/particle-usb/src/device-base.js:284:9)
    at klass.reset (/Users/keerthyamisagadda/code/particle-usb/src/device.js:167:17)
    at FlashCommand._flashFiles (/Users/keerthyamisagadda/code/particle-cli/src/cmd/flash.js:470:17)
    at async FlashCommand.flashLocal (/Users/keerthyamisagadda/code/particle-cli/src/cmd/flash.js:178:3)
    at async FlashCommand.flash (/Users/keerthyamisagadda/code/particle-cli/src/cmd/flash.js:55:4)
    at async CLI.runCommand (/Users/keerthyamisagadda/code/particle-cli/src/app/cli.js:148:4)
    at async CLI.run (/Users/keerthyamisagadda/code/particle-cli/src/app/cli.js:175:11)
npm ERR! code ELIFECYCLE
```
2. Shows an encrypted msg against progress 🤓 
```
Flashing tracker e00fce680d2c75c844999283
[████████████████████████████████████████] 100% | 2023722-72423-1dhh80i.bckl.bin
Flash success!
```

3. `--application-only` mode works great on multiple platforms!

**Comment by monkbroc** [comment]
Thanks for trying out the branch Keerthy. Can you keep notes of what doesn't work so you can re-test these with Hugo in the coming days?

**Pull request merged**
