### PR TITLE
Runtime Device OS logging configuration

### PR DESCRIPTION
**Pull request by sergeuz**
**Note: The feature implemented in this PR relies on a new Device OS functionality that has not been released yet: [device-os/#1748](https://github.com/particle-iot/device-os/pull/1748).**

This PR implements a new command called `log` that allows configuring Device OS logging at runtime. The detailed description of the command can be found in the [PRD](https://docs.google.com/document/d/14KplDrRw7Q0WNuHYpfyxIxKee_9QICiPezUa9x1Hqcc/edit?usp=sharing).

Usage:

- Enabling logging on the default `Serial` interface:
```
particle log my_device
```

- Enabling logging on the `Serial1` interface:
```
particle log my_device Serial1
```

- Showing only application messages and system errors:
```
particle log my_device -l error -f app:all
```

Example output:

pretty

### CODE REVIEW

**Comment by sergeuz** [comment]
[ch31041]

**Comment by sergeuz** [comment]
[ch30129]

**Comment by monkbroc** [comment]
From a product perspective here's what I see when I test:

When pressing reset or pulling the USB port I get a red message saying `bad file descriptor`. It would be nicer to see "connection closed" or something.

I cannot get the feature to work on a Photon, when compiling Device OS from https://github.com/particle-iot/device-os/pull/1748

**Comment by monkbroc** [comment]
I can't figure out how to use `Serial1`. It just says `Serial port is not found`.

**Comment by monkbroc** [comment]
Ah, for the serial not found I see the problem. I use a Photon with this serial echo program as my UART -> USB converter:
```
SYSTEM_MODE(MANUAL);

void setup() {
  Serial1.begin(115200);
}

void loop() {
  while(Serial1.available()) {
    char c = Serial1.read();
    Serial.write(c);
  }
}
```

Maybe just adding another example for Serial1 to show how to select a custom USB port in case the auto-detection doesn't find the right one would be enough?

**Comment by monkbroc** [comment]
I'm also not able to get any logs from `USBSerial1`. When I do 
```
$ particle log my_device USBSerial1
Opening serial port: /dev/ttyACM0
```
I get no logs.

It opens the same serial port as doing 
```
$ particle log my_device Serial
Opening serial port: /dev/ttyACM0
```

**Comment by busticated** [comment]
@sergeuz i rebased this branch against latest master. if you have work in-fligth, be sure to `git checkout -b feature/log_config_bkup` _before_ pulling.

**Comment by sergeuz** [comment]
@monkbroc I fixed the code according to your suggestions and rebased this branch. I had to disable `USBSerial1` for now, as it turned out that calling `USBSerial1.begin()` in the Device OS causes the device to be detached from the system (or otherwise invalidates the libusb handle opened by particle-usb), which in turn causes the logging request to fail

**Comment by sergeuz** [comment]
> I cannot get the feature to work on a Photon

I accidentally enabled the new logging requests only on mesh platforms. This is now fixed in https://github.com/particle-iot/device-os/pull/1748

**Comment by busticated** [comment]
@sergeuz what's the status of this work? are we still waiting for Device OS side updates?

**Comment by busticated** [comment]
this appears to be orphaned - closing. feel free to re-open when it's actionable 👍

**Comment by WakfuYT** [comment]
.

**Pull request closed without merging**
