### PR TITLE
usb: particle usb reset for devices in DFU mode

### PR DESCRIPTION
**Pull request by avtolstoy**
### Problem

https://github.com/particle-iot/particle-usb/pull/12

### Solution

Again, see https://github.com/particle-iot/particle-usb/pull/12 :smile:

For CLI specifically the only change required is to disable filtering of devices in DFU mode.

### Testing

1. ~Modify `package.json` to point to a local `particle-usb` repository pointing to https://github.com/particle-iot/particle-usb/pull/12~
2. `npm install`
3. `node dist/index.js usb reset XXXXXXXXXXXX`

### References

- [CH31926]
- https://github.com/particle-iot/particle-usb/pull/12

### CODE REVIEW

**Comment by monkbroc** [comment]
Do you know what is core-js? We're advertising for the author looking for a job with this new version apparently. It's fine, but I just wonder what it is.

image

**Comment by sergeuz** [comment]
> Do you know what is core-js?
It's an implementation of the JavaScript standard library which Babel uses for polyfilling

**Comment by busticated** [comment]
> what is core-js?

yep. bable stuff 😬

`particle-usb` might want to move to the approach we now use in here - specifically:

https://github.com/particle-iot/particle-cli/blob/master/.babelrc.js#L4-L11

more info here:

https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#usebuiltins-entry-with-corejs-3

but it's not critical 👍

**Comment by sergeuz** [comment]
> particle-usb might want to move to the approach we now use in here

particle-usb still uses the transform-runtime plugin, since `useBuiltIns: 'usage'` was an experimental feature at the time. Is it stable now?

**Comment by busticated** [comment]
> since useBuiltIns: 'usage' was an experimental feature

iirc, `entry` is / was _not_ experimental, `usage` was experimental up until `babel@7.4`. but again not a big deal for now :+1:

**Comment by sergeuz** [comment]
> iirc, entry is / was not experimental, usage was experimental up until babel@7.4

yeah, but you can't really use `entry` in a library since it overrides the globals. I actually was under impression that `usage` is going to be a `preset-env`'s alternative to `plugin-transform-runtime`, but it's not the case, and Babel folks will likely introduce a new `useBuiltins` option for use in libraries: https://github.com/babel/babel/issues/10008

**Comment by avtolstoy** [comment]
> are you ok releasing this?
@busticated Sure, I can do this today. Does this warrant an 1.42.0? Or we're fine with 1.41.1?

**Comment by busticated** [comment]
@avtolstoy incrementing the patch (`1.41.1`) seems fine

**Pull request merged**
