### PR TITLE
update binaries for Device OS v4.0.2 [sc-113462]

### PR DESCRIPTION
**Pull request by scott-brust**
## Description

Updates `particle update` binaries with Device OS 4.0.2 release binaries for gen3 platforms 

## How to Test

Update all supported platforms (ie gen3) to 4.0.2 with particle update.

## Related Issues / Discussions

https://app.shortcut.com/particle/story/113279/device-os-release-4-0-2

## Completeness

- [x] User is totes amazing for contributing!
- [ ] Contributor has signed [CLA](https://docs.google.com/a/particle.io/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform)
- [ ] Problem and solution clearly stated
- [ ] Tests have been provided
- [ ] Docs have been updated
- [ ] CI is passing

### CODE REVIEW

**Comment by keeramis** [comment]
@scott-brust I will double check how this works once again but I am wondering if we need to update here as well?
https://github.com/particle-iot/particle-cli/pull/629/files#diff-2fad2176cebef6b0a034da4cc5506fefd8a02a9654398e5a72b36fc5b9991323L64-L95

**Comment by scott-brust** [comment]
> @scott-brust I will double check how this works once again but I am wondering if we need to update here as well? https://github.com/particle-iot/particle-cli/pull/629/files#diff-2fad2176cebef6b0a034da4cc5506fefd8a02a9654398e5a72b36fc5b9991323L64-L95

Yes, forgot to commit that file!

**Review by avtolstoy — APPROVED** [review]

**Review by keeramis — APPROVED** [review]
Tested this on my local on my Boron 
```
npm start -- update
Your system firmware version is 4.0.2
```

**Review by hugomontero — APPROVED** [review]
Looks great!

**Pull request merged**
